/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    'aws_project_region': 'us-east-1',
    'aws_cognito_identity_pool_id': 'us-east-1:db23d27c-afcd-4cd8-a16e-dfee2af5af3f',
    'aws_cognito_region': 'us-east-1',
    'aws_user_pools_id': 'us-east-1_eQOIk07RR',
    'aws_user_pools_web_client_id': '7ojsvt8v06t5jn54r6j1kkempj',
    'oauth': {}
};


export default awsmobile;
